# Generated by Django 5.0.4 on 2024-05-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_taxonomy', models.CharField(default='unknown', max_length=100)),
                ('classification_type', models.CharField(default='unknown', max_length=100)),
                ('feed_accuracy', models.FloatField(blank=True, default=None, null=True)),
                ('feed_name', models.CharField(default='unknown', max_length=100)),
                ('feed_provider', models.CharField(default='unknown', max_length=100)),
                ('feed_url', models.URLField(blank=True, default=None, null=True)),
                ('protocol_application', models.CharField(default='unknown', max_length=100)),
                ('source_abuse_contact', models.CharField(default='unknown', max_length=100)),
                ('source_as_name', models.CharField(default='unknown', max_length=100)),
                ('source_asn', models.CharField(default='unknown', max_length=100)),
                ('source_geolocation_cc', models.CharField(default='unknown', max_length=100)),
                ('source_ip', models.CharField(default='unknown', max_length=100)),
                ('source_network', models.CharField(default='unknown', max_length=100)),
                ('source_registry', models.CharField(default='unknown', max_length=100)),
                ('time_observation', models.DateTimeField(blank=True, default=None, null=True)),
                ('time_source', models.DateTimeField(blank=True, default=None, null=True)),
                ('extra_blocklist', models.CharField(default='unknown', max_length=100)),
                ('source_fqdn', models.CharField(default='unknown', max_length=100)),
                ('source_port', models.CharField(default='unknown', max_length=100)),
                ('source_url', models.CharField(default='unknown', max_length=100)),
                ('source_urlpath', models.CharField(default='unknown', max_length=100)),
                ('status', models.CharField(default='unknown', max_length=100)),
                ('protocol_transport', models.CharField(default='unknown', max_length=100)),
                ('malware_name', models.CharField(default='vulnerabilities', max_length=100)),
                ('source_reverse_dns', models.CharField(default='unknown', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Threat Data ',
            },
        ),
    ]
